# Generated by Django 2.1.5 on 2019-02-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightmeasurement',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='weightmeasurement',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='weightmeasurement',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kg'), ('stone', 'Stone')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='weightmeasurement',
            name='weight_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='track.WeightRecord'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
