# Generated by Django 2.1.5 on 2019-02-26 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0002_auto_20190204_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_unit', models.CharField(choices=[('kg', 'Kg'), ('stone', 'Stone')], default='kg', max_length=10)),
                ('preferred_colour', models.CharField(default='#ff6666', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='weightmeasurement',
            options={'ordering': ['-created']},
        ),
    ]
