version: '2'
services:
    http:
        image: nginx:1.10
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - /home/pi/weighttracker/static:/static
        ports: ['80:80']
        environment:
            TZ: "CET"
        restart: always
